#### Import Files

In [ ]:
# Import Files
import pandas as pd
import numpy as np
import os
import sys
import random
import time
import matplotlib
import matplotlib.pyplot as plt
plt.grid(True)
from sklearn.svm import SVR
import pickle
from sklearn.metrics import mean_squared_error
from sklearn.neural_network import MLPRegressor
from math import sqrt

%matplotlib inline


In [ ]:
# Importing the datasets

# Mathematics Data
student_mat = pd.read_csv('./student/student-mat.csv', sep=';')

# Portuguese Data
student_por = pd.read_csv("./student/student-por.csv", sep=';')

In [ ]:
# Checking out few rows of Mathematics
student_mat.head()

school sex  age address famsize Pstatus  Medu  Fedu     Mjob      Fjob ...  \
0     GP   F   18       U     GT3       A     4     4  at_home   teacher ...   
1     GP   F   17       U     GT3       T     1     1  at_home     other ...   
2     GP   F   15       U     LE3       T     1     1  at_home     other ...   
3     GP   F   15       U     GT3       T     4     2   health  services ...   
4     GP   F   16       U     GT3       T     3     3    other     other ...   

  famrel freetime  goout  Dalc  Walc health absences  G1  G2  G3  
0      4        3      4     1     1      3        6   5   6   6  
1      5        3      3     1     1      3        4   5   5   6  
2      4        3      2     2     3      3       10   7   8  10  
3      3        2      2     1     1      5        2  15  14  15  
4      4        3      2     1     2      5        4   6  10  10  

[5 rows x 33 columns]

In [ ]:
# Checking out few rows of Portuguese
student_por.head()

school sex  age address famsize Pstatus  Medu  Fedu     Mjob      Fjob ...  \
0     GP   F   18       U     GT3       A     4     4  at_home   teacher ...   
1     GP   F   17       U     GT3       T     1     1  at_home     other ...   
2     GP   F   15       U     LE3       T     1     1  at_home     other ...   
3     GP   F   15       U     GT3       T     4     2   health  services ...   
4     GP   F   16       U     GT3       T     3     3    other     other ...   

  famrel freetime  goout  Dalc  Walc health absences  G1  G2  G3  
0      4        3      4     1     1      3        4   0  11  11  
1      5        3      3     1     1      3        2   9  11  11  
2      4        3      2     2     3      3        6  12  13  12  
3      3        2      2     1     1      5        0  14  14  14  
4      4        3      2     1     2      5        0  11  13  13  

[5 rows x 33 columns]

In [ ]:
# Number of records
print("Number of Mathematics Student Data:")
len(student_mat)

Number of Mathematics Student Data:


395

In [ ]:
# Number of records
print("Number of Portuguese Student Data:")
len(student_por)

Number of Portuguese Student Data:


649

In [ ]:
# Number of Attributes, should be 33 as specified at the data website
print("Attribute List:")
print(list(student_mat))
print()
print("Number of attributes: ", end="")
print(len(list(student_mat)))

Attribute List:
['school', 'sex', 'age', 'address', 'famsize', 'Pstatus', 'Medu', 'Fedu', 'Mjob', 'Fjob', 'reason', 'guardian', 'traveltime', 'studytime', 'failures', 'schoolsup', 'famsup', 'paid', 'activities', 'nursery', 'higher', 'internet', 'romantic', 'famrel', 'freetime', 'goout', 'Dalc', 'Walc', 'health', 'absences', 'G1', 'G2', 'G3']

Number of attributes: 33


In [ ]:
# Number of Attributes, should be 33 as specified at the data website
print("Attribute List:")
print(list(student_por))
print()
print("Number of attributes: ", end="")
print(len(list(student_por)))

Attribute List:
['school', 'sex', 'age', 'address', 'famsize', 'Pstatus', 'Medu', 'Fedu', 'Mjob', 'Fjob', 'reason', 'guardian', 'traveltime', 'studytime', 'failures', 'schoolsup', 'famsup', 'paid', 'activities', 'nursery', 'higher', 'internet', 'romantic', 'famrel', 'freetime', 'goout', 'Dalc', 'Walc', 'health', 'absences', 'G1', 'G2', 'G3']

Number of attributes: 33


## Preprocessing the data to be made ready for analysis

In [ ]:
# Copying the data, so orignal remains intact
student_mat_clean = student_mat.copy()
student_por_clean = student_por.copy()

### For Mathematics students

In [ ]:
# School
# Unique Schools
print(student_mat.school.unique())
student_mat_clean.loc[student_mat_clean['school']=='GP', 'school'] = 1
student_mat_clean.loc[student_mat_clean['school']=='MS', 'school'] = 2
print(student_mat_clean.school.unique())
print()


# Gender
# Unique Genders
print(student_mat.sex.unique())
student_mat_clean.loc[student_mat_clean['sex']=='M', 'sex'] = 1
student_mat_clean.loc[student_mat_clean['sex']=='F', 'sex'] = 2
print(student_mat_clean.sex.unique())
print()



# Address
# Unique Address
print(student_mat.address.unique())
student_mat_clean.loc[student_mat_clean['address']=='R', 'address'] = 1
student_mat_clean.loc[student_mat_clean['address']=='U', 'address'] = 2
print(student_mat_clean.address.unique())
print()

# Family Size
# Unique Family Sizes
print(student_mat.famsize.unique())
student_mat_clean.loc[student_mat_clean['famsize']=='LE3', 'famsize'] = 1
student_mat_clean.loc[student_mat_clean['famsize']=='GT3', 'famsize'] = 2
print(student_mat_clean.famsize.unique())
print()



# Parent Status
# Unique Parent Statuses
print(student_mat.Pstatus.unique())
student_mat_clean.loc[student_mat_clean['Pstatus']=='A', 'Pstatus'] = 1
student_mat_clean.loc[student_mat_clean['Pstatus']=='T', 'Pstatus'] = 2
print(student_mat_clean.Pstatus.unique())
print()


# Mother's Job Status
# Unique Mothers' jobs
print(student_mat.Mjob.unique())
student_mat_clean.loc[student_mat_clean['Mjob']=='teacher', 'Mjob'] = 5
student_mat_clean.loc[student_mat_clean['Mjob']=='services', 'Mjob'] = 4
student_mat_clean.loc[student_mat_clean['Mjob']=='health', 'Mjob'] = 3
student_mat_clean.loc[student_mat_clean['Mjob']=='other', 'Mjob'] = 2
student_mat_clean.loc[student_mat_clean['Mjob']=='at_home', 'Mjob'] = 1
print(student_mat_clean.Mjob.unique())
print()


# Father's Job Status
# Unique Fathers' jobs
print(student_mat.Fjob.unique())
student_mat_clean.loc[student_mat_clean['Fjob']=='teacher', 'Fjob'] = 5
student_mat_clean.loc[student_mat_clean['Fjob']=='services', 'Fjob'] = 4
student_mat_clean.loc[student_mat_clean['Fjob']=='health', 'Fjob'] = 3
student_mat_clean.loc[student_mat_clean['Fjob']=='other', 'Fjob'] = 2
student_mat_clean.loc[student_mat_clean['Fjob']=='at_home', 'Fjob'] = 1
print(student_mat_clean.Fjob.unique())
print()


# Reasons
# Unique Reasons
print(student_mat.reason.unique())
student_mat_clean.loc[student_mat_clean['reason']=='reputation', 'reason'] = 4
student_mat_clean.loc[student_mat_clean['reason']=='course', 'reason'] = 3
student_mat_clean.loc[student_mat_clean['reason']=='home', 'reason'] = 2
student_mat_clean.loc[student_mat_clean['reason']=='other', 'reason'] = 1
print(student_mat_clean.reason.unique())
print()




# Guardians
# Unique Guardians
print(student_mat.guardian.unique())
student_mat_clean.loc[student_mat_clean['guardian']=='father', 'guardian'] = 3
student_mat_clean.loc[student_mat_clean['guardian']=='mother', 'guardian'] = 2
student_mat_clean.loc[student_mat_clean['guardian']=='other', 'guardian'] = 1
print(student_mat_clean.guardian.unique())
print()


# School Support
# Unique School Supports
print(student_mat.schoolsup.unique())
student_mat_clean.loc[student_mat_clean['schoolsup']=='yes', 'schoolsup'] = 2
student_mat_clean.loc[student_mat_clean['schoolsup']=='no', 'schoolsup'] = 1
print(student_mat_clean.schoolsup.unique())
print()

# Family Support
# Unique Family Supports
print(student_mat.famsup.unique())
student_mat_clean.loc[student_mat_clean['famsup']=='yes', 'famsup'] = 2
student_mat_clean.loc[student_mat_clean['famsup']=='no', 'famsup'] = 1
print(student_mat_clean.famsup.unique())
print()


# Paid
# Unique Pays
print(student_mat.paid.unique())
student_mat_clean.loc[student_mat_clean['paid']=='yes', 'paid'] = 2
student_mat_clean.loc[student_mat_clean['paid']=='no', 'paid'] = 1
print(student_mat_clean.paid.unique())
print()


# Activities
# Unique Activities
print(student_mat.activities.unique())
student_mat_clean.loc[student_mat_clean['activities']=='yes', 'activities'] = 2
student_mat_clean.loc[student_mat_clean['activities']=='no', 'activities'] = 1
print(student_mat_clean.activities.unique())
print()


# Nursery
# Unique Nursery status
print(student_mat.nursery.unique())
student_mat_clean.loc[student_mat_clean['nursery']=='yes', 'nursery'] = 2
student_mat_clean.loc[student_mat_clean['nursery']=='no', 'nursery'] = 1
print(student_mat_clean.nursery.unique())
print()


# Higher Education
# Unique Higher Education status
print(student_mat.higher.unique())
student_mat_clean.loc[student_mat_clean['higher']=='yes', 'higher'] = 2
student_mat_clean.loc[student_mat_clean['higher']=='no', 'higher'] = 1
print(student_mat_clean.higher.unique())
print()

# Internet
# Unique Internet Status
print(student_mat.internet.unique())
student_mat_clean.loc[student_mat_clean['internet']=='yes', 'internet'] = 2
student_mat_clean.loc[student_mat_clean['internet']=='no', 'internet'] = 1
print(student_mat_clean.internet.unique())
print()


# Relationship
# Unique Relationship Status
print(student_mat.romantic.unique())
student_mat_clean.loc[student_mat_clean['romantic']=='yes', 'romantic'] = 2
student_mat_clean.loc[student_mat_clean['romantic']=='no', 'romantic'] = 1
print(student_mat_clean.romantic.unique())
print()






['GP' 'MS']
[1 2]

['F' 'M']
[2 1]

['U' 'R']
[2 1]

['GT3' 'LE3']
[2 1]

['A' 'T']
[1 2]

['at_home' 'health' 'other' 'services' 'teacher']
[1 3 2 4 5]

['teacher' 'other' 'services' 'health' 'at_home']
[5 2 4 3 1]

['course' 'other' 'home' 'reputation']
[3 1 2 4]

['mother' 'father' 'other']
[2 3 1]

['yes' 'no']
[2 1]

['no' 'yes']
[1 2]

['no' 'yes']
[1 2]

['no' 'yes']
[1 2]

['yes' 'no']
[2 1]

['yes' 'no']
[2 1]

['no' 'yes']
[1 2]

['no' 'yes']
[1 2]



### For Portuguese students

In [ ]:
# School
# Unique Schools
print(student_por.school.unique())
student_por_clean.loc[student_por_clean['school']=='GP', 'school'] = 1
student_por_clean.loc[student_por_clean['school']=='MS', 'school'] = 2
print(student_por_clean.school.unique())
print()


# Gender
# Unique Genders
print(student_por.sex.unique())
student_por_clean.loc[student_por_clean['sex']=='M', 'sex'] = 1
student_por_clean.loc[student_por_clean['sex']=='F', 'sex'] = 2
print(student_por_clean.sex.unique())
print()


# Address
# Unique Address
print(student_por.address.unique())
student_por_clean.loc[student_por_clean['address']=='R', 'address'] = 1
student_por_clean.loc[student_por_clean['address']=='U', 'address'] = 2
print(student_por_clean.address.unique())
print()


# Family Size
# Unique Family Sizes
print(student_por.famsize.unique())
student_por_clean.loc[student_por_clean['famsize']=='LE3', 'famsize'] = 1
student_por_clean.loc[student_por_clean['famsize']=='GT3', 'famsize'] = 2
print(student_por_clean.famsize.unique())
print()


# Parent Status
# Unique Parent Statuses
print(student_por.Pstatus.unique())
student_por_clean.loc[student_por_clean['Pstatus']=='A', 'Pstatus'] = 1
student_por_clean.loc[student_por_clean['Pstatus']=='T', 'Pstatus'] = 2
print(student_por_clean.Pstatus.unique())
print()


# Mother's Job Status
# Unique Mothers' jobs
print(student_por.Mjob.unique())
student_por_clean.loc[student_por_clean['Mjob']=='teacher', 'Mjob'] = 5
student_por_clean.loc[student_por_clean['Mjob']=='services', 'Mjob'] = 4
student_por_clean.loc[student_por_clean['Mjob']=='health', 'Mjob'] = 3
student_por_clean.loc[student_por_clean['Mjob']=='other', 'Mjob'] = 2
student_por_clean.loc[student_por_clean['Mjob']=='at_home', 'Mjob'] = 1
print(student_por_clean.Mjob.unique())
print()


# Father's Job Status
# Unique Fathers' jobs
print(student_por.Fjob.unique())
student_por_clean.loc[student_por_clean['Fjob']=='teacher', 'Fjob'] = 5
student_por_clean.loc[student_por_clean['Fjob']=='services', 'Fjob'] = 4
student_por_clean.loc[student_por_clean['Fjob']=='health', 'Fjob'] = 3
student_por_clean.loc[student_por_clean['Fjob']=='other', 'Fjob'] = 2
student_por_clean.loc[student_por_clean['Fjob']=='at_home', 'Fjob'] = 1
print(student_por_clean.Fjob.unique())
print()


# Reasons
# Unique Reasons
print(student_por.reason.unique())
student_por_clean.loc[student_por_clean['reason']=='reputation', 'reason'] = 4
student_por_clean.loc[student_por_clean['reason']=='course', 'reason'] = 3
student_por_clean.loc[student_por_clean['reason']=='home', 'reason'] = 2
student_por_clean.loc[student_por_clean['reason']=='other', 'reason'] = 1
print(student_por_clean.reason.unique())
print()




# Guardians
# Unique Guardians
print(student_por.guardian.unique())
student_por_clean.loc[student_por_clean['guardian']=='father', 'guardian'] = 3
student_por_clean.loc[student_por_clean['guardian']=='mother', 'guardian'] = 2
student_por_clean.loc[student_por_clean['guardian']=='other', 'guardian'] = 1
print(student_por_clean.guardian.unique())
print()


# School Support
# Unique School Supports
print(student_por.schoolsup.unique())
student_por_clean.loc[student_por_clean['schoolsup']=='yes', 'schoolsup'] = 2
student_por_clean.loc[student_por_clean['schoolsup']=='no', 'schoolsup'] = 1
print(student_por_clean.schoolsup.unique())
print()

# Family Support
# Unique Family Supports
print(student_por.famsup.unique())
student_por_clean.loc[student_por_clean['famsup']=='yes', 'famsup'] = 2
student_por_clean.loc[student_por_clean['famsup']=='no', 'famsup'] = 1
print(student_por_clean.famsup.unique())
print()


# Paid
# Unique Pays
print(student_por.paid.unique())
student_por_clean.loc[student_por_clean['paid']=='yes', 'paid'] = 2
student_por_clean.loc[student_por_clean['paid']=='no', 'paid'] = 1
print(student_por_clean.paid.unique())
print()


# Activities
# Unique Activities
print(student_por.activities.unique())
student_por_clean.loc[student_por_clean['activities']=='yes', 'activities'] = 2
student_por_clean.loc[student_por_clean['activities']=='no', 'activities'] = 1
print(student_por_clean.activities.unique())
print()


# Nursery
# Unique Nursery status
print(student_por.nursery.unique())
student_por_clean.loc[student_por_clean['nursery']=='yes', 'nursery'] = 2
student_por_clean.loc[student_por_clean['nursery']=='no', 'nursery'] = 1
print(student_por_clean.nursery.unique())
print()


# Higher Education
# Unique Higher Education status
print(student_por.higher.unique())
student_por_clean.loc[student_por_clean['higher']=='yes', 'higher'] = 2
student_por_clean.loc[student_por_clean['higher']=='no', 'higher'] = 1
print(student_por_clean.higher.unique())
print()

# Internet
# Unique Internet Status
print(student_por.internet.unique())
student_por_clean.loc[student_por_clean['internet']=='yes', 'internet'] = 2
student_por_clean.loc[student_por_clean['internet']=='no', 'internet'] = 1
print(student_por_clean.internet.unique())
print()


# Relationship
# Unique Relationship Status
print(student_por.romantic.unique())
student_por_clean.loc[student_por_clean['romantic']=='yes', 'romantic'] = 2
student_por_clean.loc[student_por_clean['romantic']=='no', 'romantic'] = 1
print(student_por_clean.romantic.unique())
print()



['GP' 'MS']
[1 2]

['F' 'M']
[2 1]

['U' 'R']
[2 1]

['GT3' 'LE3']
[2 1]

['A' 'T']
[1 2]

['at_home' 'health' 'other' 'services' 'teacher']
[1 3 2 4 5]

['teacher' 'other' 'services' 'health' 'at_home']
[5 2 4 3 1]

['course' 'other' 'home' 'reputation']
[3 1 2 4]

['mother' 'father' 'other']
[2 3 1]

['yes' 'no']
[2 1]

['no' 'yes']
[1 2]

['no' 'yes']
[1 2]

['no' 'yes']
[1 2]

['yes' 'no']
[2 1]

['yes' 'no']
[2 1]

['no' 'yes']
[1 2]

['no' 'yes']
[1 2]



### 1> Applying SVR (Support Vector Machine Regression)

#### Mathematics Training and Testing Sets

In [ ]:
mat_data_training = student_mat_clean.loc[:380, :'G2']
mat_label_training = student_mat_clean.loc[:380, 'G3' :'G3']
mat_label_training = mat_label_training.values.flatten()

mat_data_testing = student_mat_clean.loc[380:, :'G2']
mat_label_testing = student_mat_clean.loc[380:, 'G3' :'G3']


#### Portuguese Training and Testing Sets

In [ ]:
por_data_training = student_por_clean.loc[:380, :'G2']
por_label_training = student_por_clean.loc[:380, 'G3' :'G3']
por_label_training = por_label_training.values.flatten()

por_data_testing = student_por_clean.loc[380:, :'G2']
por_label_testing = student_por_clean.loc[380:, 'G3' :'G3']

#### SVR Mathematics

In [ ]:
# Defining 1 degree SVM Regression
clf_1 = SVR(C=0.2, epsilon=0.2, kernel='poly', degree=1)

# Fitting SVR
clf_1.fit(mat_data_training, mat_label_training.ravel())

# Saving SVR Model
check = pickle.dumps(clf_1)

# Predicting the list
clf_1_results = clf_1.predict(mat_data_testing).tolist()


# Root Mean Square Error
mse = mean_squared_error(clf_1_results, mat_label_testing)
mse_scaled = sqrt(mse)
print(mse_scaled)

2.3871997924492248


In [ ]:

# Predicting the list
clf_1_results_check = clf_1.predict(mat_data_testing).tolist()
print(clf_1_results_check)

[14.268600637351652, 5.964835357544858, 11.021182648169232, 4.993448919670088, 5.252168620104827, 9.211315360812074, 4.976637682742412, 5.218641546866717, 8.894297791366458, 4.752724133358809, 9.081857169048803, 15.806491925735644, 8.169828640858572, 12.135118165752049, 8.817922672503022]


#### SVR Portuguese

In [ ]:
# Defining 1 degree SVM Regression
clf_2 = SVR(C=0.2, epsilon=0.2, kernel='poly', degree=1)

# Fitting SVR
clf_2.fit(por_data_training, por_label_training)

# Saving SVR Model
check = pickle.dumps(clf_2)

# Predicting the list
clf_2_results = clf_2.predict(por_data_testing).tolist()

mse = mean_squared_error(clf_2_results, por_label_testing)
mse_scaled = sqrt(mse)
print(mse_scaled)

1.6101637568037925


### 2> Applying Neural Networks for prediction

#### For Mathematics

In [ ]:
mlp_ann = MLPRegressor(max_iter=10000)
mat_ann = mlp_ann.fit(mat_data_training, mat_label_training)
mat_predict_ann = mat_ann.predict(mat_data_testing)

In [ ]:
mse2 = mean_squared_error(mat_predict_ann, mat_label_testing)
mse2_scaled = sqrt(mse2)
print(mse2_scaled)

6.347631795264142


#### For Portuguese

In [ ]:
por_mlp_ann = MLPRegressor(max_iter=10000)
por_ann = por_mlp_ann.fit(por_data_training, por_label_training)
por_predict_ann = por_ann.predict(por_data_testing)

In [ ]:
mse2 = mean_squared_error(por_predict_ann, por_label_testing)
mse2_scaled = sqrt(mse2)
print(mse2_scaled)

4.181582650333204
